// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMsg.proto

package com.union.netty4.serialization.protobuf.message;

public final class ProtoMsg {
  private ProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.union.netty4.serialization.protobuf.message.BaseMsgInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 msg_id_client = 1;</code>
     * @return The msgIdClient.
     */
    long getMsgIdClient();

    /**
     * <code>uint64 msg_id_server = 2;</code>
     * @return The msgIdServer.
     */
    long getMsgIdServer();
  }
  /**
   * Protobuf type {@code com.union.netty4.serialization.protobuf.message.BaseMsgInfo}
   */
  public static final class BaseMsgInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.union.netty4.serialization.protobuf.message.BaseMsgInfo)
      BaseMsgInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsgInfo.newBuilder() to construct.
    private BaseMsgInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsgInfo() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseMsgInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMsgInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgIdClient_ = input.readUInt64();
              break;
            }
            case 16: {

              msgIdServer_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMsgInfo.class, Builder.class);
    }

    public static final int MSG_ID_CLIENT_FIELD_NUMBER = 1;
    private long msgIdClient_;
    /**
     * <code>uint64 msg_id_client = 1;</code>
     * @return The msgIdClient.
     */
    @Override
    public long getMsgIdClient() {
      return msgIdClient_;
    }

    public static final int MSG_ID_SERVER_FIELD_NUMBER = 2;
    private long msgIdServer_;
    /**
     * <code>uint64 msg_id_server = 2;</code>
     * @return The msgIdServer.
     */
    @Override
    public long getMsgIdServer() {
      return msgIdServer_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgIdClient_ != 0L) {
        output.writeUInt64(1, msgIdClient_);
      }
      if (msgIdServer_ != 0L) {
        output.writeUInt64(2, msgIdServer_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgIdClient_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgIdClient_);
      }
      if (msgIdServer_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, msgIdServer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BaseMsgInfo)) {
        return super.equals(obj);
      }
      BaseMsgInfo other = (BaseMsgInfo) obj;

      if (getMsgIdClient()
          != other.getMsgIdClient()) return false;
      if (getMsgIdServer()
          != other.getMsgIdServer()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgIdClient());
      hash = (37 * hash) + MSG_ID_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgIdServer());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BaseMsgInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BaseMsgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BaseMsgInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.union.netty4.serialization.protobuf.message.BaseMsgInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.union.netty4.serialization.protobuf.message.BaseMsgInfo)
        BaseMsgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMsgInfo.class, Builder.class);
      }

      // Construct using com.union.netty4.serialization.protobuf.message.ProtoMsg.BaseMsgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgIdClient_ = 0L;

        msgIdServer_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor;
      }

      @Override
      public BaseMsgInfo getDefaultInstanceForType() {
        return BaseMsgInfo.getDefaultInstance();
      }

      @Override
      public BaseMsgInfo build() {
        BaseMsgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BaseMsgInfo buildPartial() {
        BaseMsgInfo result = new BaseMsgInfo(this);
        result.msgIdClient_ = msgIdClient_;
        result.msgIdServer_ = msgIdServer_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMsgInfo) {
          return mergeFrom((BaseMsgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMsgInfo other) {
        if (other == BaseMsgInfo.getDefaultInstance()) return this;
        if (other.getMsgIdClient() != 0L) {
          setMsgIdClient(other.getMsgIdClient());
        }
        if (other.getMsgIdServer() != 0L) {
          setMsgIdServer(other.getMsgIdServer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMsgInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMsgInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgIdClient_ ;
      /**
       * <code>uint64 msg_id_client = 1;</code>
       * @return The msgIdClient.
       */
      @Override
      public long getMsgIdClient() {
        return msgIdClient_;
      }
      /**
       * <code>uint64 msg_id_client = 1;</code>
       * @param value The msgIdClient to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdClient(long value) {
        
        msgIdClient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 msg_id_client = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgIdClient() {
        
        msgIdClient_ = 0L;
        onChanged();
        return this;
      }

      private long msgIdServer_ ;
      /**
       * <code>uint64 msg_id_server = 2;</code>
       * @return The msgIdServer.
       */
      @Override
      public long getMsgIdServer() {
        return msgIdServer_;
      }
      /**
       * <code>uint64 msg_id_server = 2;</code>
       * @param value The msgIdServer to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdServer(long value) {
        
        msgIdServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 msg_id_server = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgIdServer() {
        
        msgIdServer_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.union.netty4.serialization.protobuf.message.BaseMsgInfo)
    }

    // @@protoc_insertion_point(class_scope:com.union.netty4.serialization.protobuf.message.BaseMsgInfo)
    private static final BaseMsgInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BaseMsgInfo();
    }

    public static BaseMsgInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsgInfo>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsgInfo>() {
      @Override
      public BaseMsgInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMsgInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsgInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BaseMsgInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public BaseMsgInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.union.netty4.serialization.protobuf.message.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     * @return Whether the baseMsgInfo field is set.
     */
    boolean hasBaseMsgInfo();
    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     * @return The baseMsgInfo.
     */
    BaseMsgInfo getBaseMsgInfo();
    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     */
    BaseMsgInfoOrBuilder getBaseMsgInfoOrBuilder();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    String getPassword();
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.union.netty4.serialization.protobuf.message.Login}
   */
  public static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.union.netty4.serialization.protobuf.message.Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      name_ = "";
      password_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              BaseMsgInfo.Builder subBuilder = null;
              if (baseMsgInfo_ != null) {
                subBuilder = baseMsgInfo_.toBuilder();
              }
              baseMsgInfo_ = input.readMessage(BaseMsgInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseMsgInfo_);
                baseMsgInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.class, Builder.class);
    }

    public static final int BASE_MSG_INFO_FIELD_NUMBER = 1;
    private BaseMsgInfo baseMsgInfo_;
    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     * @return Whether the baseMsgInfo field is set.
     */
    @Override
    public boolean hasBaseMsgInfo() {
      return baseMsgInfo_ != null;
    }
    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     * @return The baseMsgInfo.
     */
    @Override
    public BaseMsgInfo getBaseMsgInfo() {
      return baseMsgInfo_ == null ? BaseMsgInfo.getDefaultInstance() : baseMsgInfo_;
    }
    /**
     * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
     */
    @Override
    public BaseMsgInfoOrBuilder getBaseMsgInfoOrBuilder() {
      return getBaseMsgInfo();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile Object password_;
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    @Override
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    @Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseMsgInfo_ != null) {
        output.writeMessage(1, getBaseMsgInfo());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseMsgInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseMsgInfo());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Login)) {
        return super.equals(obj);
      }
      Login other = (Login) obj;

      if (hasBaseMsgInfo() != other.hasBaseMsgInfo()) return false;
      if (hasBaseMsgInfo()) {
        if (!getBaseMsgInfo()
            .equals(other.getBaseMsgInfo())) return false;
      }
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseMsgInfo()) {
        hash = (37 * hash) + BASE_MSG_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getBaseMsgInfo().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.union.netty4.serialization.protobuf.message.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.union.netty4.serialization.protobuf.message.Login)
        LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.class, Builder.class);
      }

      // Construct using com.union.netty4.serialization.protobuf.message.ProtoMsg.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (baseMsgInfoBuilder_ == null) {
          baseMsgInfo_ = null;
        } else {
          baseMsgInfo_ = null;
          baseMsgInfoBuilder_ = null;
        }
        name_ = "";

        password_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor;
      }

      @Override
      public Login getDefaultInstanceForType() {
        return Login.getDefaultInstance();
      }

      @Override
      public Login build() {
        Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Login buildPartial() {
        Login result = new Login(this);
        if (baseMsgInfoBuilder_ == null) {
          result.baseMsgInfo_ = baseMsgInfo_;
        } else {
          result.baseMsgInfo_ = baseMsgInfoBuilder_.build();
        }
        result.name_ = name_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login) {
          return mergeFrom((Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login other) {
        if (other == Login.getDefaultInstance()) return this;
        if (other.hasBaseMsgInfo()) {
          mergeBaseMsgInfo(other.getBaseMsgInfo());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private BaseMsgInfo baseMsgInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseMsgInfo, BaseMsgInfo.Builder, BaseMsgInfoOrBuilder> baseMsgInfoBuilder_;
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       * @return Whether the baseMsgInfo field is set.
       */
      public boolean hasBaseMsgInfo() {
        return baseMsgInfoBuilder_ != null || baseMsgInfo_ != null;
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       * @return The baseMsgInfo.
       */
      public BaseMsgInfo getBaseMsgInfo() {
        if (baseMsgInfoBuilder_ == null) {
          return baseMsgInfo_ == null ? BaseMsgInfo.getDefaultInstance() : baseMsgInfo_;
        } else {
          return baseMsgInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public Builder setBaseMsgInfo(BaseMsgInfo value) {
        if (baseMsgInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseMsgInfo_ = value;
          onChanged();
        } else {
          baseMsgInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public Builder setBaseMsgInfo(
          BaseMsgInfo.Builder builderForValue) {
        if (baseMsgInfoBuilder_ == null) {
          baseMsgInfo_ = builderForValue.build();
          onChanged();
        } else {
          baseMsgInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public Builder mergeBaseMsgInfo(BaseMsgInfo value) {
        if (baseMsgInfoBuilder_ == null) {
          if (baseMsgInfo_ != null) {
            baseMsgInfo_ =
              BaseMsgInfo.newBuilder(baseMsgInfo_).mergeFrom(value).buildPartial();
          } else {
            baseMsgInfo_ = value;
          }
          onChanged();
        } else {
          baseMsgInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public Builder clearBaseMsgInfo() {
        if (baseMsgInfoBuilder_ == null) {
          baseMsgInfo_ = null;
          onChanged();
        } else {
          baseMsgInfo_ = null;
          baseMsgInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public BaseMsgInfo.Builder getBaseMsgInfoBuilder() {
        
        onChanged();
        return getBaseMsgInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      public BaseMsgInfoOrBuilder getBaseMsgInfoOrBuilder() {
        if (baseMsgInfoBuilder_ != null) {
          return baseMsgInfoBuilder_.getMessageOrBuilder();
        } else {
          return baseMsgInfo_ == null ?
              BaseMsgInfo.getDefaultInstance() : baseMsgInfo_;
        }
      }
      /**
       * <code>.com.union.netty4.serialization.protobuf.message.BaseMsgInfo base_msg_info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BaseMsgInfo, BaseMsgInfo.Builder, BaseMsgInfoOrBuilder>
          getBaseMsgInfoFieldBuilder() {
        if (baseMsgInfoBuilder_ == null) {
          baseMsgInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BaseMsgInfo, BaseMsgInfo.Builder, BaseMsgInfoOrBuilder>(
                  getBaseMsgInfo(),
                  getParentForChildren(),
                  isClean());
          baseMsgInfo_ = null;
        }
        return baseMsgInfoBuilder_;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>string password = 3;</code>
       * @return The password.
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.union.netty4.serialization.protobuf.message.Login)
    }

    // @@protoc_insertion_point(class_scope:com.union.netty4.serialization.protobuf.message.Login)
    private static final Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Login();
    }

    public static Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @Override
    public Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.union.netty4.serialization.protobuf.message.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     * @return Whether the login field is set.
     */
    boolean hasLogin();
    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     * @return The login.
     */
    Login getLogin();
    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     */
    LoginOrBuilder getLoginOrBuilder();
  }
  /**
   * Protobuf type {@code com.union.netty4.serialization.protobuf.message.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.union.netty4.serialization.protobuf.message.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Login.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(Login.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.class, Builder.class);
    }

    private int bitField0_;
    public static final int LOGIN_FIELD_NUMBER = 1;
    private Login login_;
    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     * @return Whether the login field is set.
     */
    @Override
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     * @return The login.
     */
    @Override
    public Login getLogin() {
      return login_ == null ? Login.getDefaultInstance() : login_;
    }
    /**
     * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
     */
    @Override
    public LoginOrBuilder getLoginOrBuilder() {
      return login_ == null ? Login.getDefaultInstance() : login_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getLogin());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLogin());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Msg)) {
        return super.equals(obj);
      }
      Msg other = (Msg) obj;

      if (hasLogin() != other.hasLogin()) return false;
      if (hasLogin()) {
        if (!getLogin()
            .equals(other.getLogin())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLogin()) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.union.netty4.serialization.protobuf.message.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.union.netty4.serialization.protobuf.message.Msg)
        MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.class, Builder.class);
      }

      // Construct using com.union.netty4.serialization.protobuf.message.ProtoMsg.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLoginFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (loginBuilder_ == null) {
          login_ = null;
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor;
      }

      @Override
      public Msg getDefaultInstanceForType() {
        return Msg.getDefaultInstance();
      }

      @Override
      public Msg build() {
        Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Msg buildPartial() {
        Msg result = new Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (loginBuilder_ == null) {
            result.login_ = login_;
          } else {
            result.login_ = loginBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg) {
          return mergeFrom((Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg other) {
        if (other == Msg.getDefaultInstance()) return this;
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Login login_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Login, Login.Builder, LoginOrBuilder> loginBuilder_;
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       * @return Whether the login field is set.
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       * @return The login.
       */
      public Login getLogin() {
        if (loginBuilder_ == null) {
          return login_ == null ? Login.getDefaultInstance() : login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public Builder setLogin(Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public Builder setLogin(
          Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public Builder mergeLogin(Login value) {
        if (loginBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              login_ != null &&
              login_ != Login.getDefaultInstance()) {
            login_ =
              Login.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = null;
          onChanged();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public Login.Builder getLoginBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      public LoginOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_ == null ?
              Login.getDefaultInstance() : login_;
        }
      }
      /**
       * <code>optional .com.union.netty4.serialization.protobuf.message.Login login = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Login, Login.Builder, LoginOrBuilder>
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Login, Login.Builder, LoginOrBuilder>(
                  getLogin(),
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.union.netty4.serialization.protobuf.message.Msg)
    }

    // @@protoc_insertion_point(class_scope:com.union.netty4.serialization.protobuf.message.Msg)
    private static final Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Msg();
    }

    public static Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @Override
    public Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_union_netty4_serialization_protobuf_message_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_union_netty4_serialization_protobuf_message_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016ProtoMsg.proto\022/com.union.netty4.seria" +
      "lization.protobuf.message\";\n\013BaseMsgInfo" +
      "\022\025\n\rmsg_id_client\030\001 \001(\004\022\025\n\rmsg_id_server" +
      "\030\002 \001(\004\"|\n\005Login\022S\n\rbase_msg_info\030\001 \001(\0132<" +
      ".com.union.netty4.serialization.protobuf" +
      ".message.BaseMsgInfo\022\014\n\004name\030\002 \001(\t\022\020\n\010pa" +
      "ssword\030\003 \001(\t\"[\n\003Msg\022J\n\005login\030\001 \001(\01326.com" +
      ".union.netty4.serialization.protobuf.mes" +
      "sage.LoginH\000\210\001\001B\010\n\006_loginb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_union_netty4_serialization_protobuf_message_BaseMsgInfo_descriptor,
        new String[] { "MsgIdClient", "MsgIdServer", });
    internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_union_netty4_serialization_protobuf_message_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_union_netty4_serialization_protobuf_message_Login_descriptor,
        new String[] { "BaseMsgInfo", "Name", "Password", });
    internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_union_netty4_serialization_protobuf_message_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_union_netty4_serialization_protobuf_message_Msg_descriptor,
        new String[] { "Login", "Login", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
